# Generated by Django 2.1 on 2019-04-07 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=8000)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.Language')),
            ],
        ),
    ]
