# Generated by Django 2.1 on 2019-04-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20190412_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
