# Generated by Django 2.1 on 2019-04-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_auto_20190412_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibilites',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
