# Generated by Django 2.1 on 2019-04-12 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_responsibilites_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responsibilites',
            new_name='Responsibilities',
        ),
    ]
