# Generated by Django 2.1 on 2019-04-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_auto_20190412_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishments',
            name='rank',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
